spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: prod
  application:
    name: AbsensiApps
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50