spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${HOST_TEST}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}



  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect