spring:
  profiles:
    active: test
  application:
    name: AbsensiApps
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
    default-model-rendering: example
    deep-linking: true




logging:
  file:
    name: logs/app.log