-- Flyway Script: V2__insert_employee_attendance.sql

-- 1. INSERT semua data Employee. Ini harus menjadi pernyataan terpisah.
INSERT INTO employee (id, created_at, updated_at, user_name, first_name, last_name, role)
VALUES
    (RANDOM_UUID(), NOW(), NOW(), 'budi.santoso', 'Budi', 'Santoso', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'siti.rahma', 'Siti', 'Rahma', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'agus.wibowo', 'Agus', 'Wibowo', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'dewi.lestari', 'Dewi', 'Lestari', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'andi.pratama', 'Andi', 'Pratama', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'ratna.putri', 'Ratna', 'Putri', 'PERSIAPAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'joko.susanto', 'Joko', 'Susanto', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'nina.anggraini', 'Nina', 'Anggraini', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'rio.hidayat', 'Rio', 'Hidayat', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'mega.kartika', 'Mega', 'Kartika', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'yusuf.anwar', 'Yusuf', 'Anwar', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'ayu.wulandari', 'Ayu', 'Wulandari', 'PERSIAPAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'eko.susilo', 'Eko', 'Susilo', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'lina.wardani', 'Lina', 'Wardani', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'adi.firmansyah', 'Adi', 'Firmansyah', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'fitri.yuliana', 'Fitri', 'Yuliana', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'tono.subroto', 'Tono', 'Subroto', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'dian.kusuma', 'Dian', 'Kusuma', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'rahmat.setiawan', 'Rahmat', 'Setiawan', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'tika.maharani', 'Tika', 'Maharani', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'bayu.nugroho', 'Bayu', 'Nugroho', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'laila.rosita', 'Laila', 'Rosita', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'arif.kurniawan', 'Arif', 'Kurniawan', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'melati.safira', 'Melati', 'Safira', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'indra.maulana', 'Indra', 'Maulana', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'wulan.permata', 'Wulan', 'Permata', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'reza.hakim', 'Reza', 'Hakim', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'yuli.astuti', 'Yuli', 'Astuti', 'PERSIAPAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'fajar.syahputra', 'Fajar', 'Syahputra', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'rina.amalia', 'Rina', 'Amalia', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'taufik.hidayat', 'Taufik', 'Hidayat', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'sri.rahayu', 'Sri', 'Rahayu', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'hasan.basri', 'Hasan', 'Basri', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'yani.rosmini', 'Yani', 'Rosmini', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'ilham.fauzi', 'Ilham', 'Fauzi', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'maya.susilowati', 'Maya', 'Susilowati', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'zaki.mubarok', 'Zaki', 'Mubarok', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'nisa.wardah', 'Nisa', 'Wardah', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'dedi.gunawan', 'Dedi', 'Gunawan', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'salsa.rahmi', 'Salsa', 'Rahmi', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'omar.ramadhan', 'Omar', 'Ramadhan', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'citra.anindya', 'Citra', 'Anindya', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'aldi.prasetyo', 'Aldi', 'Prasetyo', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'nurul.fadhilah', 'Nurul', 'Fadhilah', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'fauzan.ridho', 'Fauzan', 'Ridho', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'sarah.kemala', 'Sarah', 'Kemala', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'miko.hartono', 'Miko', 'Hartono', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'jihan.anggun', 'Jihan', 'Anggun', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'ahmad.syafii', 'Ahmad', 'Syafii', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'tania.mulyani', 'Tania', 'Mulyani', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'farhan.hidayat', 'Farhan', 'Hidayat', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'syifa.rahmania', 'Syifa', 'Rahmania', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'arjuna.wijaya', 'Arjuna', 'Wijaya', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'karina.febrianti', 'Karina', 'Febrianti', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'panji.surya', 'Panji', 'Surya', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'okta.wardhani', 'Okta', 'Wardhani', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'bambang.supriyadi', 'Bambang', 'Supriyadi', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'tasya.indriani', 'Tasya', 'Indriani', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'rizky.saputra', 'Rizky', 'Saputra', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'alya.cahyani', 'Alya', 'Cahyani', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'hilman.firmansyah', 'Hilman', 'Firmansyah', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'yana.sundari', 'Yana', 'Sundari', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'gilang.purnama', 'Gilang', 'Purnama', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'della.putri', 'Della', 'Putri', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'faizal.muttaqin', 'Faizal', 'Muttaqin', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'tari.safitri', 'Tari', 'Safitri', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'agusman.siregar', 'Agusman', 'Siregar', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'maria.novita', 'Maria', 'Novita', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'yoga.wijayanto', 'Yoga', 'Wijayanto', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'rina.karlina', 'Rina', 'Karlina', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'reza.prakoso', 'Reza', 'Prakoso', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'tiwi.andriana', 'Tiwi', 'Andriana', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'fadhil.muhammad', 'Fadhil', 'Muhammad', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'nadya.fauziah', 'Nadya', 'Fauziah', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'roni.kusnadi', 'Roni', 'Kusnadi', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'salsa.bella', 'Salsa', 'Bella', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'angga.trianda', 'Angga', 'Trianda', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'veronica.amanda', 'Veronica', 'Amanda', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'ferry.hermawan', 'Ferry', 'Hermawan', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'dini.hartati', 'Dini', 'Hartati', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'hanif.satrio', 'Hanif', 'Satrio', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'nabila.ismail', 'Nabila', 'Ismail', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'lukman.hakim', 'Lukman', 'Hakim', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'syahrul.ramli', 'Syahrul', 'Ramli', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'yuni.anggraini', 'Yuni', 'Anggraini', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'prasetya.darmawan', 'Prasetya', 'Darmawan', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'devy.arlita', 'Devy', 'Arlita', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'hendri.suryana', 'Hendri', 'Suryana', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'putri.ayu', 'Putri', 'Ayu', 'CUCI'),
    (RANDOM_UUID(), NOW(), NOW(), 'irwan.syah', 'Irwan', 'Syah', 'SATPAM'),
    (RANDOM_UUID(), NOW(), NOW(), 'cindy.oktaviani', 'Cindy', 'Oktaviani', 'PEMORSIAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'mira.lestari', 'Mira', 'Lestari', 'MASAK'),
    (RANDOM_UUID(), NOW(), NOW(), 'samsul.bahri', 'Samsul', 'Bahri', 'AKUNTAN'),
    (RANDOM_UUID(), NOW(), NOW(), 'ulfa.fatimah', 'Ulfa', 'Fatimah', 'DISTRIBUTOR'),
    (RANDOM_UUID(), NOW(), NOW(), 'galih.saputra', 'Galih', 'Saputra', 'ASLAP'),
    (RANDOM_UUID(), NOW(), NOW(), 'alya.hanifah', 'Alya', 'Hanifah', 'GIZI'),
    (RANDOM_UUID(), NOW(), NOW(), 'habib.syukur', 'Habib', 'Syukur', 'PEMORSIAN');

-- 2. INSERT data Kehadiran (Attendance) dengan merujuk ID Employee
--    Ini menggunakan sub-query untuk mencari ID UUID berdasarkan user_name yang unik.

INSERT INTO attendance (id, employee_id, attendance_date, status, created_at, updated_at)
SELECT
    RANDOM_UUID(),
    (SELECT id FROM employee WHERE user_name = user_data.user_name), -- Cari ID berdasarkan user_name
    CURRENT_DATE,
    user_data.status,
    NOW(),
    NOW()
FROM (
         -- Data dummy untuk kehadiran
         VALUES
             ('budi.santoso', 'HADIR'),
             ('siti.rahma', 'SAKIT'),
             ('agus.wibowo', 'SAKIT'),
             ('dewi.lestari', 'HADIR'),
             ('andi.pratama', 'IZIN'),
             ('ratna.putri', 'HADIR'),
             ('joko.susanto', 'HADIR'),
             ('nina.anggraini', 'HADIR'),
             ('rio.hidayat', 'HADIR'),
             ('mega.kartika', 'HADIR'),
             ('yusuf.anwar', 'IZIN'),
             ('ayu.wulandari', 'HADIR'),
             ('eko.susilo', 'HADIR'),
             ('lina.wardani', 'SAKIT'),
             ('adi.firmansyah', 'HADIR'),
             ('fitri.yuliana', 'HADIR'),
             ('tono.subroto', 'HADIR'),
             ('dian.kusuma', 'HADIR'),
             ('rahmat.setiawan', 'HADIR'),
             ('tika.maharani', 'HADIR'),
             ('bayu.nugroho', 'HADIR'),
             ('laila.rosita', 'HADIR'),
             ('arif.kurniawan', 'HADIR'),
             ('melati.safira', 'HADIR'),
             ('indra.maulana', 'HADIR'),
             ('wulan.permata', 'HADIR'),
             ('reza.hakim', 'HADIR'),
             ('yuli.astuti', 'SAKIT'),
             ('fajar.syahputra', 'HADIR'),
             ('rina.amalia', 'HADIR'),
             ('taufik.hidayat', 'HADIR'),
             ('sri.rahayu', 'HADIR'),
             ('hasan.basri', 'HADIR'),
             ('yani.rosmini', 'HADIR'),
             ('ilham.fauzi', 'HADIR'),
             ('maya.susilowati', 'HADIR'),
             ('zaki.mubarok', 'HADIR'),
             ('nisa.wardah', 'HADIR'),
             ('dedi.gunawan', 'HADIR'),
             ('salsa.rahmi', 'HADIR'),
             ('omar.ramadhan', 'HADIR'),
             ('citra.anindya', 'HADIR'),
             ('aldi.prasetyo', 'HADIR'),
             ('nurul.fadhilah', 'HADIR'),
             ('fauzan.ridho', 'HADIR'),
             ('sarah.kemala', 'HADIR'),
             ('miko.hartono', 'HADIR'),
             ('jihan.anggun', 'HADIR'),
             ('ahmad.syafii', 'HADIR'),
             ('tania.mulyani', 'HADIR'),
             ('farhan.hidayat', 'HADIR'),
             ('syifa.rahmania', 'HADIR'),
             ('arjuna.wijaya', 'HADIR'),
             ('karina.febrianti', 'HADIR'),
             ('panji.surya', 'HADIR'),
             ('okta.wardhani', 'HADIR'),
             ('bambang.supriyadi', 'HADIR'),
             ('tasya.indriani', 'HADIR'),
             ('rizky.saputra', 'HADIR'),
             ('alya.cahyani', 'HADIR'),
             ('hilman.firmansyah', 'HADIR'),
             ('yana.sundari', 'HADIR'),
             ('gilang.purnama', 'HADIR'),
             ('della.putri', 'HADIR'),
             ('faizal.muttaqin', 'HADIR'),
             ('tari.safitri', 'HADIR'),
             ('agusman.siregar', 'HADIR'),
             ('maria.novita', 'HADIR'),
             ('yoga.wijayanto', 'HADIR'),
             ('rina.karlina', 'HADIR'),
             ('reza.prakoso', 'HADIR'),
             ('tiwi.andriana', 'HADIR'),
             ('fadhil.muhammad', 'HADIR'),
             ('nadya.fauziah', 'HADIR'),
             ('roni.kusnadi', 'HADIR'),
             ('salsa.bella', 'HADIR'),
             ('angga.trianda', 'HADIR'),
             ('veronica.amanda', 'HADIR'),
             ('ferry.hermawan', 'HADIR'),
             ('dini.hartati', 'HADIR'),
             ('hanif.satrio', 'HADIR'),
             ('nabila.ismail', 'HADIR'),
             ('lukman.hakim', 'HADIR'),
             ('syahrul.ramli', 'HADIR'),
             ('yuni.anggraini', 'HADIR'),
             ('prasetya.darmawan', 'HADIR'),
             ('devy.arlita', 'HADIR'),
             ('hendri.suryana', 'HADIR'),
             ('putri.ayu', 'HADIR'),
             ('irwan.syah', 'HADIR'),
             ('cindy.oktaviani', 'HADIR'),
             ('mira.lestari', 'HADIR'),
             ('samsul.bahri', 'HADIR'),
             ('ulfa.fatimah', 'HADIR'),
             ('galih.saputra', 'IZIN'),
             ('alya.hanifah', 'HADIR'),
             ('habib.syukur', 'HADIR')
         ) AS user_data(user_name, status);